-- 환자 정보
CREATE TABLE MEDICAL_MEMBER(
  MEM_NUM VARCHAR(20) PRIMARY KEY
  ,MEM_NAME VARCHAR(20) NOT NULL
  ,MEM_TEL VARCHAR(50) NOT NULL UNIQUE
  ,MEM_RRN VARCHAR(20) UNIQUE NOT NULL
  ,MEM_ROLE VARCHAR(30) DEFAULT('USER')
);
-- DROP TABLE
DROP TABLE MEDICAL_MEMBER;
DROP TABLE medical_dept;
DROP TABLE medical_doctor;
DROP TABLE medical_schedule;

-- 회원가입 정보 INSERT
INSERT INTO medical_member (
	MEM_NUM
  ,MEM_NAME
  ,MEM_TEL
  ,MEM_RRN
)VALUES (
	'0'
  ,'김수한무'
  ,'01011112222'
  ,'9604232222222'
);
SELECT * FROM medical_member;

-- 진료과
CREATE TABLE MEDICAL_DEPT(
	DEPT_NUM INT PRIMARY KEY
	,DEPT_NAME VARCHAR(30) NOT NULL
);
-- 진료과 insert
INSERT INTO medical_dept(DEPT_NUM, DEPT_NAME) VALUES(1, '유방암 외과');
INSERT INTO medical_dept(DEPT_NUM, DEPT_NAME) VALUES(2, '신경외과');
INSERT INTO medical_dept(DEPT_NUM, DEPT_NAME) VALUES(3, '갑상선 외과');
INSERT INTO medical_dept(DEPT_NUM, DEPT_NAME) VALUES(4, '산부인과');
INSERT INTO medical_dept(DEPT_NUM, DEPT_NAME) VALUES(5, '흉부외과');
INSERT INTO medical_dept(DEPT_NUM, DEPT_NAME) VALUES(6, '혈액 종양 내과');

-- 의료진
CREATE TABLE MEDICAL_DOCTOR(
	DOC_NUM VARCHAR(20) PRIMARY KEY
	,DOC_NAME VARCHAR(20) NOT NULL
	,DEPT_NUM INT REFERENCES MEDICAL_DEPT(DEPT_NUM)
);
SELECT * FROM medical_dept;
SELECT * FROM medical_doctor;

DELETE FROM medical_doctor;

UPDATE medical_doctor
SET DOC_NAME = '정다영'
WHERE DOC_NUM = 6;

-- 의료진 insert
INSERT INTO medical_doctor VALUES ('1','김현경', 1);
INSERT INTO medical_doctor VALUES ('2','민정흠', 2);
INSERT INTO medical_doctor VALUES ('3','유지현', 3);
INSERT INTO medical_doctor VALUES ('4','서은송', 4);
INSERT INTO medical_doctor VALUES ('5','김형진', 5);
INSERT INTO medical_doctor VALUES ('6','김하루', 6);

-- 의료진, 의사 JOIN select
SELECT DOC_NAME, DEPT_NAME
FROM medical_dept, medical_doctor
WHERE medical_dept.DEPT_NUM = medical_doctor.DEPT_NUM;

-- 예약
CREATE TABLE MEDICAL_SCHEDULE(
  SCH_NUM INT PRIMARY KEY AUTO_INCREMENT
  ,DOC_NUM VARCHAR(20) REFERENCES medical_doctor(DOC_NUM) ON DELETE CASCADE
  ,MEM_NUM VARCHAR(20) REFERENCES medical_member(MEM_NUM) ON DELETE CASCADE
  ,DEPT_NUM INT REFERENCES medical_dept(DEPT_NUM) ON DELETE CASCADE -- 진료과 번호 조인
  ,REG_DATE DATETIME DEFAULT CURRENT_TIMESTAMP -- 접수날짜
  ,SCH_DATE DATE NOT NULL -- 예약날짜 년월일
  ,SCH_TIME TIME NOT NULL -- 예약 날짜 시간
  ,DETAIL VARCHAR(100)
  ,SCH_STATUS VARCHAR(10) DEFAULT('Y')  
);
SELECT * FROM medical_schedule;

DELETE FROM user_board;
SELECT * FROM user_board;
SELECT * FROM medical_member;
DROP TABLE user_board;
-- 게시판
CREATE TABLE USER_BOARD(
BOARD_NUM INT AUTO_INCREMENT PRIMARY KEY
, TITLE VARCHAR(20) NOT NULL
, WRITER VARCHAR(10) NOT NULL
, CONTENT VARCHAR(1000) NOT NULL
, CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP
, MEM_NUM VARCHAR(20) REFERENCES medical_member(MEM_NUM)
);
SELECT * FROM user_board;
-- 이미지
CREATE TABLE DOCTOR_IMG(
IMG_NUM INT PRIMARY KEY AUTO_INCREMENT
, ORIGIN_FILE_NAME VARCHAR(20)
, ATTACHED_FILE_NAME VARCHAR(20) NOT NULL
, DOC_NUM VARCHAR(20) REFERENCES medical_doctor(DOC_NUM)
);
