-- 환자 정보
CREATE TABLE MEDICAL_MEMBER(
	MEM_NUM INT PRIMARY KEY AUTO_INCREMENT
	,MEM_NAME VARCHAR(20) NOT NULL
	,MEM_TEL VARCHAR(50) NOT NULL UNIQUE
	,MEM_RRN VARCHAR(20) UNIQUE NOT NULL
	,MEM_ROLE VARCHAR(30) DEFAULT('USER')
);

-- 진료과
CREATE TABLE MEDICAL_DEPT(
	DEPT_NUM INT PRIMARY KEY
	,DEPT_NAME VARCHAR(30) NOT NULL
	
);

-- 의료진
CREATE TABLE MEDICAL_DOCTOR(
	DOC_NUM INT PRIMARY KEY AUTO_INCREMENT
	,DOC_NAME VARCHAR(20) NOT NULL
	,DEPT_NUM INT REFERENCES MEDICAL_DEPT(DEPT_NUM)
	
);
-- 예약
CREATE TABLE (
	SCH_NUM INT PRIMARY KEY AUTO_INCREMENT
	,DOC_NUM INT REFERENCES MEDICAL_DOCTOR(DOC_NUM)
	,MEM_NUM INT REFERENCES MEDICAL_MEMBER(MEM_NUM)
	,REG_DATE DATETIME DEFAULT CURRENT_TIMESTAMP -- 접수날짜
	,SCH_DATE DATETIME -- 예약날짜 건들일 예정
	,DETAIL VARCHAR(100)
	,SCH_STATUS VARCHAR(10) DEFAULT('Y')
);
